/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

#include "gui_entry.h"
#include "gui_menu.h"
#include "gui_history.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x0F)
#define ID_BUTTON_ACTUAL   (GUI_ID_USER + 0x11)
#define ID_BUTTON_STORAGE  (GUI_ID_USER + 0x12)


// USER START (Optionally insert additional defines)
extern  gui_dev_t g_gui_dev;
// USER END

#define TITLE_SIZEY  40
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static U8 _g_state = 0;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, TITLE_SIZEY, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ACTUAL",   ID_BUTTON_ACTUAL, 0, 0, 120, TITLE_SIZEY, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "STORAGE",  ID_BUTTON_STORAGE, 120, 0, 120, TITLE_SIZEY, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _button_disable(WM_HWIN hWin,int id) {
	WM_HWIN hItem;

	hItem = WM_GetDialogItem(hWin, id);
	WM_DisableWindow(hItem);

	if (id != ID_BUTTON_ACTUAL) {
		hItem = WM_GetDialogItem(hWin, ID_BUTTON_ACTUAL);
		WM_EnableWindow(hItem);
	} 
	if (id != ID_BUTTON_STORAGE) {
		hItem = WM_GetDialogItem(hWin, ID_BUTTON_STORAGE);
		WM_EnableWindow(hItem);
	}
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  WM_HWIN hItem;

  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	  hItem =  WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ACTUAL);
	  BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLUE);
	  BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_WHITE);
	  BUTTON_SetBkColor(hItem,BUTTON_CI_DISABLED,0xfcffe9);
	  BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_BLUE);
      BUTTON_SetFont(hItem,&GUI_Font16B_ASCII);

	  hItem =  WM_GetDialogItem(pMsg->hWin, ID_BUTTON_STORAGE);
	  BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLUE);
	  BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_WHITE);
	  BUTTON_SetBkColor(hItem,BUTTON_CI_DISABLED,0xfcffe9);
	  BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_BLUE);
	  BUTTON_SetFont(hItem,&GUI_Font16B_ASCII);

	_button_disable(pMsg->hWin, ID_BUTTON_ACTUAL);
	  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_ACTUAL: // Notifications sent by 'INPUT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  WM_DeleteWindow(g_gui_dev.hMenuHistory);
		  g_gui_dev.hMenuWin = CreateMenu();
		  _button_disable(pMsg->hWin, ID_BUTTON_ACTUAL);
          _g_state = 0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_STORAGE: // Notifications sent by 'STORAGE'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  WM_DeleteWindow(g_gui_dev.hMenuWin);
		  g_gui_dev.hMenuHistory = CreateHistory();
		  _button_disable(pMsg->hWin, ID_BUTTON_STORAGE);
          _g_state = 1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
		
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateTitle(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

//获取当前状态
U8 gui_state_get(void)
{
    return _g_state;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
