/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "gui_entry.h"

#include <string.h>
#include <stdio.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_0 (GUI_ID_USER + 0x05)
#define ID_BUTTON_1 (GUI_ID_USER + 0x06)
#define ID_TEXT_4 (GUI_ID_USER + 0x07)
#define ID_TEXT_5 (GUI_ID_USER + 0x08)
#define ID_TEXT_6 (GUI_ID_USER + 0x09)
#define ID_TEXT_7 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0C)


#define _X1POS   10
#define _X2POS   110

#define _XBTNADD   _X2POS + 80 
#define _XBTNCUT   _X2POS - _SIZEBTNX

#define _YOFFSET  30
#define _Y1   ((280 / 5) * 0 + _YOFFSET)
#define _Y2   ((280 / 5) * 1 + _YOFFSET)
#define _Y3   ((280 / 5) * 2 + _YOFFSET)
#define _Y4   ((280 / 5) * 3 + _YOFFSET)

#define _SIZEBTNX  20
#define _SIZEBTNY  20

// USER START (Optionally insert additional defines)
extern  gui_dev_t g_gui_dev;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static WM_MESSAGE __g_pMsg;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 40, 240, 280, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Speed:",   ID_TEXT_0,   _X1POS,   _Y1, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0m/s",     ID_TEXT_1,   _X2POS,   _Y1, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Time",     ID_TEXT_2,   _X1POS,   _Y2, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "1s",       ID_TEXT_3,   _X2POS,   _Y2, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-",      ID_BUTTON_0, _XBTNCUT, _Y2 + 10, _SIZEBTNX, _SIZEBTNY, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+",      ID_BUTTON_1, _XBTNADD, _Y2 + 10, _SIZEBTNX, _SIZEBTNY, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Dire:",    ID_TEXT_4,   _X1POS,   _Y3, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "200",      ID_TEXT_5,   _X2POS,   _Y3, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Time",     ID_TEXT_6,   _X1POS,   _Y4, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "2s",       ID_TEXT_7,   _X2POS,   _Y4, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-",      ID_BUTTON_2, _XBTNCUT, _Y4 + 10, _SIZEBTNX, _SIZEBTNY, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+",      ID_BUTTON_3, _XBTNADD, _Y4 + 10, _SIZEBTNX, _SIZEBTNY, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

void _dire_estab(U16 dire, WM_HWIN hItem)
{
	static char buf[10];
	U8 a = dire % 90;
	U8 b = dire / 90;

	memset(buf, 0, 10);
	if (a == 0) {
		switch (b)
		{
		case 0:
			TEXT_SetText(hItem, "south");
			break;
		case 1:
			TEXT_SetText(hItem, "west");
			break;
		case 2:
			TEXT_SetText(hItem, "north");
			break;
		case 3:
			TEXT_SetText(hItem, "east");
			break;
		default:
			break;
		}
	}
	else {
		switch (b)
		{
		case 0:
			sprintf(buf, "S->W %d", a);
			break;
		case 1:
			sprintf(buf, "W->N %d", a);
			break;
		case 2:
			sprintf(buf, "N->E %d", a);
			break;
		case 3:
			sprintf(buf, "E->S %d", a);
			break;
		default:
			break;
		}

		TEXT_SetText(hItem, buf);
	}

	

}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;

  WM_HWIN hItem;
  char buf[10];


  __g_pMsg.MsgId = WM_PAINT;
  
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_PAINT:
	  GUI_SetColor(0x762646);              /* 设置分隔线横条颜色 */
	  GUI_DrawHLine(_Y1 + 35, 10, 300);
	  GUI_DrawHLine(_Y2 + 35, 10, 300);
	  GUI_DrawHLine(_Y3 + 35, 10, 300);
	  GUI_DrawHLine(_Y4 + 35, 10, 300);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	  sprintf(buf, "%d.%d m/s", g_gui_dev.speed / 10,g_gui_dev.speed % 10);
	  TEXT_SetText(hItem,buf);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	  sprintf(buf, "%d s", g_gui_dev.time_speed);
	  TEXT_SetText(hItem, buf);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
	  _dire_estab(g_gui_dev.dire, hItem);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
	  sprintf(buf, "%d s", g_gui_dev.time_dire);
	  TEXT_SetText(hItem, buf);


	  break;
  case WM_INIT_DIALOG:
	  WINDOW_SetBkColor(pMsg->hWin, 0xE6E6E6);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	  TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	  TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
	  TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
	  TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	  TEXT_SetTextAlign(hItem, TEXT_CF_VCENTER);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	  TEXT_SetTextAlign(hItem, TEXT_CF_VCENTER);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
	  TEXT_SetTextAlign(hItem, TEXT_CF_VCENTER);

	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
	  TEXT_SetTextAlign(hItem, TEXT_CF_VCENTER);
	  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  if (g_gui_dev.time_speed != 1) {
			  g_gui_dev.time_speed--;
			  WM_SendMessage(g_gui_dev.hMenuWin, &__g_pMsg);
		  }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  if (g_gui_dev.time_speed != 10) {
			  g_gui_dev.time_speed++;
			  WM_SendMessage(g_gui_dev.hMenuWin, &__g_pMsg);
		  }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  if (g_gui_dev.time_dire != 1) {
			  g_gui_dev.time_dire--;
			  WM_SendMessage(g_gui_dev.hMenuWin, &__g_pMsg);
		  }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  if (g_gui_dev.time_dire != 10) {
			  g_gui_dev.time_dire++;
			  WM_SendMessage(g_gui_dev.hMenuWin, &__g_pMsg);
		  }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateMenu(void) {
  WM_HWIN hWin;
  TEXT_SetDefaultFont(&GUI_FontComic18B_1);
  BUTTON_SetDefaultTextAlign(GUI_TA_HCENTER | GUI_TA_VCENTER);
  BUTTON_SetDefaultFont(&GUI_FontComic18B_1);
  

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

//更新风速值
void gui_speed_update(U16 speed)
{
	g_gui_dev.speed = speed;

	__g_pMsg.MsgId = WM_PAINT;
	WM_SendMessage(g_gui_dev.hMenuWin, &__g_pMsg);
}

//更新风向值
void gui_dire_update(U16 dire)
{
	g_gui_dev.dire = dire;

	__g_pMsg.MsgId = WM_PAINT;
	WM_SendMessage(g_gui_dev.hMenuWin, &__g_pMsg);
}

//获取风速采样值
U8 gui_speed_time_get(void)
{
    return g_gui_dev.time_speed;
}

//获取风向采样值
U8 gui_dire_time_get(void)
{
    return g_gui_dev.time_dire;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
