/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "gui_entry.h"

#include <stdio.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x01)
#define ID_BUTTON_1  (GUI_ID_USER + 0x02)
#define ID_TEXT_PAGE (GUI_ID_USER + 0x03)

#define ID_TEXT_1    (GUI_ID_USER + 0x04)
#define ID_TEXT_2    (GUI_ID_USER + 0x05)
#define ID_TEXT_3    (GUI_ID_USER + 0x06)
#define ID_TEXT_4    (GUI_ID_USER + 0x07)
#define ID_TEXT_5    (GUI_ID_USER + 0x08)
#define ID_TEXT_6    (GUI_ID_USER + 0x09)
#define ID_TEXT_7    (GUI_ID_USER + 0x0a)
#define ID_TEXT_8    (GUI_ID_USER + 0x0b)
#define ID_TEXT_9    (GUI_ID_USER + 0x0c)
#define ID_TEXT_10   (GUI_ID_USER + 0x0d)

#define ID_TEXT_11    (GUI_ID_USER + 0x14)
#define ID_TEXT_12    (GUI_ID_USER + 0x15)
#define ID_TEXT_13    (GUI_ID_USER + 0x16)
#define ID_TEXT_14    (GUI_ID_USER + 0x17)
#define ID_TEXT_15    (GUI_ID_USER + 0x18)
#define ID_TEXT_16    (GUI_ID_USER + 0x19)
#define ID_TEXT_17    (GUI_ID_USER + 0x1a)
#define ID_TEXT_18    (GUI_ID_USER + 0x1b)
#define ID_TEXT_19    (GUI_ID_USER + 0x1c)
#define ID_TEXT_20   (GUI_ID_USER + 0x1d)



#define _TEXT_Y1   20
#define _TEXT_Y2   (20 + _TEXT_Y1)
#define _TEXT_Y3   (20 + _TEXT_Y2)
#define _TEXT_Y4   (20 + _TEXT_Y3)
#define _TEXT_Y5   (20 + _TEXT_Y4)
#define _TEXT_Y6   (20 + _TEXT_Y5)
#define _TEXT_Y7   (20 + _TEXT_Y6)
#define _TEXT_Y8   (20 + _TEXT_Y7)
#define _TEXT_Y9   (20 + _TEXT_Y8)
#define _TEXT_Y10  (20 + _TEXT_Y9)

#define _TEXT_X1   30
#define _TEXT_X2   130

// USER START (Optionally insert additional defines)
extern  gui_dev_t g_gui_dev;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static char _g_dire_buf[10][10];
static char _g_page_buf[10];
static char _g_speed_buf[10][10];



static U8 __g_state = 0;

static WM_MESSAGE __g_pMsg;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 40, 240, 280, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "<", ID_BUTTON_0, 20, 240, 70, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ">", ID_BUTTON_1, 150, 240, 70, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "1/10",ID_TEXT_PAGE,   100,   240, 40, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_1,   _TEXT_X1,   _TEXT_Y1, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_2,   _TEXT_X1,   _TEXT_Y2, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_3,   _TEXT_X1,   _TEXT_Y3, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_4,   _TEXT_X1,   _TEXT_Y4, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_5,   _TEXT_X1,   _TEXT_Y5, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_6,   _TEXT_X1,   _TEXT_Y6, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_7,   _TEXT_X1,   _TEXT_Y7, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_8,   _TEXT_X1,   _TEXT_Y8, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_9,   _TEXT_X1,   _TEXT_Y9, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_10,  _TEXT_X1,   _TEXT_Y10, 80, 20, 0, 0x0, 0 },

  { TEXT_CreateIndirect, "123",   ID_TEXT_11,   _TEXT_X2,   _TEXT_Y1, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_12,   _TEXT_X2,   _TEXT_Y2, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_13,   _TEXT_X2,   _TEXT_Y3, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_14,   _TEXT_X2,   _TEXT_Y4, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_15,   _TEXT_X2,   _TEXT_Y5, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_16,   _TEXT_X2,   _TEXT_Y6, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_17,   _TEXT_X2,   _TEXT_Y7, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_18,   _TEXT_X2,   _TEXT_Y8, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_19,   _TEXT_X2,   _TEXT_Y9, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "123",   ID_TEXT_20,   _TEXT_X2,   _TEXT_Y10, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;

  WM_HWIN hItem;

  int testid1 = ID_TEXT_1;
  int testid2 = ID_TEXT_11;
  int i = 0;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_PAINT:
	  for (i = 0; i < 11; i++)
	  {
		  hItem = WM_GetDialogItem(pMsg->hWin, (testid1 + i));
		  TEXT_SetText(hItem, _g_speed_buf[i]);
		  TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);

		  hItem = WM_GetDialogItem(pMsg->hWin, (testid2 + i));
		  TEXT_SetText(hItem, _g_dire_buf[i]);
		  TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
	  }
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PAGE);
	  TEXT_SetText(hItem, _g_page_buf);
	  TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);

	  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '<'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        __g_state = 1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '>'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        __g_state = 2;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateHistory(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}


static void _dire_estab(U16 dire, char *p_buf)
{
	U8 a = dire % 90;
	U8 b = dire / 90;
	if (a == 0) {
		switch (b)
		{
		case 0:
			sprintf(p_buf, "south");
			break;
		case 1:
			sprintf(p_buf, "west");
			break;
		case 2:
			sprintf(p_buf, "north");
			break;
		case 3:
			sprintf(p_buf, "east");
			break;
		default:
			break;
		}
	}
	else {
		switch (b)
		{
		case 0:
			sprintf(p_buf, "S->W %d", a);
			break;
		case 1:
			sprintf(p_buf, "W->N %d", a);
			break;
		case 2:
			sprintf(p_buf, "N->E %d", a);
			break;
		case 3:
			sprintf(p_buf, "E->S %d", a);
			break;
		default:
			break;
		}
	}



}
void gui_history_dataupdata(U8 *p_buf, U8 size, U8 now_page, U8 all_page)
{
	U8  i = 0;
	U8  speed = 0;
	U16 dire = 0;

	size %= 11;
	all_page %= 11;
	now_page %= 11;


	for ( i = 0; i < size; i++)
	{
		speed = p_buf[3 * i];
		dire = (U16)p_buf[3 * i + 1] * 256 + p_buf[3 * i + 2];

		sprintf(_g_speed_buf[i],"%d.%d m/s", (speed/10), (speed%10));
		_dire_estab(dire, _g_dire_buf[i]);
	}

	for (i = size; i <= 10; i++) {
		sprintf(_g_speed_buf[i], " ");
		sprintf(_g_dire_buf[i], " ");
	}

	sprintf(_g_page_buf, "%d/%d", now_page, all_page);

	__g_pMsg.MsgId = WM_PAINT;

	WM_SendMessage(g_gui_dev.hMenuHistory, &__g_pMsg);
}


//获取状态上一页  返回1  下一页返回2  无操作返回0
U8 gui_gistory_state_get(void)
{
    U8 state = __g_state;
    __g_state = 0;
    
    return state;
}
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
